name: stockfish_flutter_plus
description: The Stockfish Chess Engine for Flutter.
version: 1.0.0
homepage: https://github.com/Dexterfury/stockfish_flutter_plus
repository: https://github.com/Dexterfury/stockfish_flutter_plus

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.stockfish
        pluginClass: StockfishPlugin
      ios:
        pluginClass: StockfishPlugin
